version: '3'
networks:
  pond_network:
    external: true
services:
  questdb:
    image: questdb/questdb:7.0.0
    container_name: questdb
    restart: always
    ports:
      - 9000:9000 #REST API and Web Console
      - 9009:9009 #InfluxDB line protocol
      - 8812:8812 #Postgres wire protocol
      - 9003:9003 #Min health server and Prometheus metrics
    volumes:
      - ./../resources/questdb/conf/server.conf:/root/.questdb/conf/server.conf
      - ./../resources/questdb/conf/log.conf:/root/.questdb/conf/log.conf
      - ./../resources/questdb/conf/auth.txt:/root/.questdb/conf/auth.txt
      - ./volumes/questdb/db:/root/.questdb/db
    networks:
      - pond_network
  questdb_setup:
    image: alpine/curl:latest
    restart: on-failure
    networks:
      - pond_network
    depends_on:
      - questdb
    volumes:
      - ./../resources:/resources
    command: ./resources/scripts/questdb_setup.sh questdb:9000
