version: '3'

services:
  rest_api:
    container_name: frog
    restart: always
    build: ./frog/docker
    ports:
      - 8000:8000
    depends_on:
      - postgresql
      - questdb
  postgresql:
    extends:
      file: ./databases/docker-compose.yml
      service: postgresql
  pgadmin:
    extends:
      file: ./databases/docker-compose.yml
      service: pgadmin
  questdb:
    extends:
      file: ./databases/docker-compose.yml
      service: questdb
  questdb_setup:
    extends:
      file: ./databases/docker-compose.yml
      service: questdb_setup
    depends_on:
      - questdb