version: '3'

services:
  rest_api:
    container_name: frog
    build: ./frog/docker
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
      - questdb
  postgresql:
    extends:
      file: ./database/postgresql/docker/docker-compose.yml
      service: postgresql
  questdb:
    extends:
      file: ./database/questdb/docker/docker-compose.yml
      service: questdb