version: '3'

services:
  db:
    image: postgres:15
    container_name: pond_postgresql
    restart: always
    ports:
      - 5400:5432
    environment:
      POSTGRES_DB: frog
      POSTGRES_USER: frog
      POSTGRES_PASSWORD: frog!123
    volumes:
      - ./../resources/init.sql:/docker-entrypoint-initdb.d/init.sql