version: '3'

services:
  questdb:
    image: questdb/questdb:7.0.0
    container_name: pond_questdb
    restart: always
    ports:
      - 9000:9000
      - 9009:9009
      - 8812:8812
      - 9003:9003
    volumes:
      - ./questdb:/root/.questdb