version: '3'

services:
  postgresql:
    image: postgres:15
    container_name: pond_postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: frog
      POSTGRES_USER: frog
      POSTGRES_PASSWORD: frog!123
    volumes:
      - ./../resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volumins/postgres-data:/var/lib/postgresql/data