version: '3'

networks:
  pond_network:
    external: true

services:
  toad:
    restart: always
    build: ./docker
    ports:
      - 1883:1883
      - 5570:5570
      - 5571:5571
    networks:
      - pond_network
