version: '3'

networks:
  pond_network:
    external: true

services:
  toad:
    restart: always
    build: ./docker
    ports:
      - 1883:1883 # mqtt
      - 5570:5570 # tcp
      - 5571:5571 # requester
      - 5572:5572 # notifier
    networks:
      - pond_network
