version: '3'
networks:
  moja_siec:
    external: true
services:
  postgresql:
    extends:
      file: ./postgresql/docker/docker-compose.yml
      service: postgresql
  pgadmin:
    extends:
      file: ./postgresql/docker/docker-compose.yml
      service: pgadmin
  questdb:
    extends:
      file: ./questdb/docker/docker-compose.yml
      service: questdb
  questdb_setup:
    depends_on:
      - questdb
    extends:
      file: ./questdb/docker/docker-compose.yml
      service: questdb_setup