version: '3'
networks:
  pond_network:
    external: true
services:
  postgresql:
    image: postgres:15
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: frog
      POSTGRES_USER: frog
      POSTGRES_PASSWORD: frog!123
    volumes:
      - ./../resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volumes/postgres-data:/var/lib/postgresql/data
    networks:
      - pond_network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    depends_on:
      - postgresql
    restart: always
    ports:
      - 5050:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_SERVER_JSON_FILE: ./../resources/servers.json
    volumes:
      - ./../resources/servers.json:/pgadmin4/servers.json
      - ./../resources/pgpassfile.config:/pgadmin4/pgpassfile.config
    networks:
      - pond_network
