version: '3'
networks:
  moja_siec:
    external: true
services:
  postgresql:
    image: postgres:15
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: frog
      POSTGRES_USER: frog
      POSTGRES_PASSWORD: frog!123
    volumes:
      - ./../resources/init-smart_terrarium.sql:/docker-entrypoint-initdb.d/init-smart_terrarium.sql
      - ./volumes/postgres-data:/var/lib/postgresql/data
    networks:
      - moja_siec
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    depends_on:
      - postgresql
    restart: always
    ports:
      - 5050:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    networks:
      - moja_siec
